# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: button.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='button.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62utton.proto\"I\n\rButtonRequest\x12\x1d\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\r.ButtonAction\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ButtonType\"/\n\x0e\x42uttonResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.ButtonStatus*4\n\x0c\x42uttonAction\x12\x0b\n\x07TURN_ON\x10\x00\x12\x0c\n\x08TURN_OFF\x10\x01\x12\t\n\x05\x43HECK\x10\x02*4\n\nButtonType\x12\x07\n\x03\x43\x43\x44\x10\x00\x12\x08\n\x04TELE\x10\x01\x12\x08\n\x04\x46LAT\x10\x02\x12\t\n\x05LIGHT\x10\x03*\x1f\n\x0c\x42uttonStatus\x12\x06\n\x02ON\x10\x00\x12\x07\n\x03OFF\x10\x01\x32\x36\n\x06\x42utton\x12,\n\tSetAction\x12\x0e.ButtonRequest\x1a\x0f.ButtonResponseb\x06proto3'
)

_BUTTONACTION = _descriptor.EnumDescriptor(
  name='ButtonAction',
  full_name='ButtonAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TURN_ON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TURN_OFF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_BUTTONACTION)

ButtonAction = enum_type_wrapper.EnumTypeWrapper(_BUTTONACTION)
_BUTTONTYPE = _descriptor.EnumDescriptor(
  name='ButtonType',
  full_name='ButtonType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CCD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TELE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLAT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIGHT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=246,
)
_sym_db.RegisterEnumDescriptor(_BUTTONTYPE)

ButtonType = enum_type_wrapper.EnumTypeWrapper(_BUTTONTYPE)
_BUTTONSTATUS = _descriptor.EnumDescriptor(
  name='ButtonStatus',
  full_name='ButtonStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=248,
  serialized_end=279,
)
_sym_db.RegisterEnumDescriptor(_BUTTONSTATUS)

ButtonStatus = enum_type_wrapper.EnumTypeWrapper(_BUTTONSTATUS)
TURN_ON = 0
TURN_OFF = 1
CHECK = 2
CCD = 0
TELE = 1
FLAT = 2
LIGHT = 3
ON = 0
OFF = 1



_BUTTONREQUEST = _descriptor.Descriptor(
  name='ButtonRequest',
  full_name='ButtonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ButtonRequest.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ButtonRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=89,
)


_BUTTONRESPONSE = _descriptor.Descriptor(
  name='ButtonResponse',
  full_name='ButtonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ButtonResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=138,
)

_BUTTONREQUEST.fields_by_name['action'].enum_type = _BUTTONACTION
_BUTTONREQUEST.fields_by_name['type'].enum_type = _BUTTONTYPE
_BUTTONRESPONSE.fields_by_name['status'].enum_type = _BUTTONSTATUS
DESCRIPTOR.message_types_by_name['ButtonRequest'] = _BUTTONREQUEST
DESCRIPTOR.message_types_by_name['ButtonResponse'] = _BUTTONRESPONSE
DESCRIPTOR.enum_types_by_name['ButtonAction'] = _BUTTONACTION
DESCRIPTOR.enum_types_by_name['ButtonType'] = _BUTTONTYPE
DESCRIPTOR.enum_types_by_name['ButtonStatus'] = _BUTTONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonRequest = _reflection.GeneratedProtocolMessageType('ButtonRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONREQUEST,
  '__module__' : 'button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonRequest)
  })
_sym_db.RegisterMessage(ButtonRequest)

ButtonResponse = _reflection.GeneratedProtocolMessageType('ButtonResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONRESPONSE,
  '__module__' : 'button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonResponse)
  })
_sym_db.RegisterMessage(ButtonResponse)



_BUTTON = _descriptor.ServiceDescriptor(
  name='Button',
  full_name='Button',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetAction',
    full_name='Button.SetAction',
    index=0,
    containing_service=None,
    input_type=_BUTTONREQUEST,
    output_type=_BUTTONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUTTON)

DESCRIPTOR.services_by_name['Button'] = _BUTTON

# @@protoc_insertion_point(module_scope)
