# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curtains.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='curtains.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63urtains.proto\"Z\n\x0e\x43urtainRequest\x12\x1e\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0e.CurtainAction\x12(\n\x0borientation\x18\x02 \x01(\x0e\x32\x13.CurtainOrientation\"[\n\x0f\x43urtainResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.CurtainStatus\x12(\n\x0borientation\x18\x02 \x01(\x0e\x32\x13.CurtainOrientation*K\n\rCurtainAction\x12\n\n\x06\x45NABLE\x10\x00\x12\x0b\n\x07\x44ISABLE\x10\x01\x12\x16\n\x12\x43\x41LIBRATE_CURTAINS\x10\x02\x12\t\n\x05\x43HECK\x10\x03*(\n\x12\x43urtainOrientation\x12\x08\n\x04\x45\x41ST\x10\x00\x12\x08\n\x04WEST\x10\x01*s\n\rCurtainStatus\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\n\n\x06\x43LOSED\x10\x01\x12\x0b\n\x07STOPPED\x10\x02\x12\n\n\x06OPENED\x10\x03\x12\x0b\n\x07\x43LOSING\x10\x04\x12\x0b\n\x07OPENING\x10\x05\x12\n\n\x06\x44\x41NGER\x10\x06\x12\t\n\x05\x45RROR\x10\x07\x32\x39\n\x07\x43urtain\x12.\n\tSetAction\x12\x0f.CurtainRequest\x1a\x10.CurtainResponseb\x06proto3'
)

_CURTAINACTION = _descriptor.EnumDescriptor(
  name='CurtainAction',
  full_name='CurtainAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENABLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_CURTAINS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_CURTAINACTION)

CurtainAction = enum_type_wrapper.EnumTypeWrapper(_CURTAINACTION)
_CURTAINORIENTATION = _descriptor.EnumDescriptor(
  name='CurtainOrientation',
  full_name='CurtainOrientation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EAST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=280,
  serialized_end=320,
)
_sym_db.RegisterEnumDescriptor(_CURTAINORIENTATION)

CurtainOrientation = enum_type_wrapper.EnumTypeWrapper(_CURTAINORIENTATION)
_CURTAINSTATUS = _descriptor.EnumDescriptor(
  name='CurtainStatus',
  full_name='CurtainStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DANGER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=322,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_CURTAINSTATUS)

CurtainStatus = enum_type_wrapper.EnumTypeWrapper(_CURTAINSTATUS)
ENABLE = 0
DISABLE = 1
CALIBRATE_CURTAINS = 2
CHECK = 3
EAST = 0
WEST = 1
DISABLED = 0
CLOSED = 1
STOPPED = 2
OPENED = 3
CLOSING = 4
OPENING = 5
DANGER = 6
ERROR = 7



_CURTAINREQUEST = _descriptor.Descriptor(
  name='CurtainRequest',
  full_name='CurtainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='CurtainRequest.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='CurtainRequest.orientation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=108,
)


_CURTAINRESPONSE = _descriptor.Descriptor(
  name='CurtainResponse',
  full_name='CurtainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='CurtainResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='CurtainResponse.orientation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=201,
)

_CURTAINREQUEST.fields_by_name['action'].enum_type = _CURTAINACTION
_CURTAINREQUEST.fields_by_name['orientation'].enum_type = _CURTAINORIENTATION
_CURTAINRESPONSE.fields_by_name['status'].enum_type = _CURTAINSTATUS
_CURTAINRESPONSE.fields_by_name['orientation'].enum_type = _CURTAINORIENTATION
DESCRIPTOR.message_types_by_name['CurtainRequest'] = _CURTAINREQUEST
DESCRIPTOR.message_types_by_name['CurtainResponse'] = _CURTAINRESPONSE
DESCRIPTOR.enum_types_by_name['CurtainAction'] = _CURTAINACTION
DESCRIPTOR.enum_types_by_name['CurtainOrientation'] = _CURTAINORIENTATION
DESCRIPTOR.enum_types_by_name['CurtainStatus'] = _CURTAINSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurtainRequest = _reflection.GeneratedProtocolMessageType('CurtainRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURTAINREQUEST,
  '__module__' : 'curtains_pb2'
  # @@protoc_insertion_point(class_scope:CurtainRequest)
  })
_sym_db.RegisterMessage(CurtainRequest)

CurtainResponse = _reflection.GeneratedProtocolMessageType('CurtainResponse', (_message.Message,), {
  'DESCRIPTOR' : _CURTAINRESPONSE,
  '__module__' : 'curtains_pb2'
  # @@protoc_insertion_point(class_scope:CurtainResponse)
  })
_sym_db.RegisterMessage(CurtainResponse)



_CURTAIN = _descriptor.ServiceDescriptor(
  name='Curtain',
  full_name='Curtain',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=439,
  serialized_end=496,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetAction',
    full_name='Curtain.SetAction',
    index=0,
    containing_service=None,
    input_type=_CURTAINREQUEST,
    output_type=_CURTAINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURTAIN)

DESCRIPTOR.services_by_name['Curtain'] = _CURTAIN

# @@protoc_insertion_point(module_scope)
