# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crac_protobuf/button.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63rac_protobuf/button.proto\"\x10\n\x0e\x42uttonsRequest\"I\n\rButtonRequest\x12\x1d\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\r.ButtonAction\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ButtonType\"3\n\x0f\x42uttonsResponse\x12 \n\x07\x62uttons\x18\x01 \x03(\x0b\x32\x0f.ButtonResponse\"j\n\x0e\x42uttonResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.ButtonStatus\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ButtonType\x12\x1e\n\nbutton_gui\x18\x03 \x01(\x0b\x32\n.ButtonGui\"\xe5\x01\n\tButtonGui\x12\x1f\n\x08metadata\x18\x01 \x01(\x0e\x32\r.ButtonAction\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bis_disabled\x18\x03 \x01(\x08\x12\"\n\x0c\x62utton_color\x18\x04 \x01(\x0b\x32\x0c.ButtonColor\x12\x12\n\nis_visible\x18\x05 \x01(\x08\x12+\n\x15\x64isabled_button_color\x18\x06 \x01(\x0b\x32\x0c.ButtonColor\x12\"\n\x0c\x62utton_image\x18\x07 \x01(\x0b\x32\x0c.ButtonImage\x12\x0b\n\x03key\x18\x08 \x01(\t\";\n\x0b\x42uttonColor\x12\x12\n\ntext_color\x18\x01 \x01(\t\x12\x18\n\x10\x62\x61\x63kground_color\x18\x02 \x01(\t\"Z\n\x0b\x42uttonImage\x12\x12\n\nimage_data\x18\x01 \x01(\t\x12\x17\n\x0fimage_subsample\x18\x02 \x01(\x05\x12\x1e\n\x04size\x18\x03 \x01(\x0b\x32\x10.ButtonImageSize\"0\n\x0f\x42uttonImageSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05*V\n\x0c\x42uttonAction\x12\x19\n\x15\x42UTTON_DEFAULT_ACTION\x10\x00\x12\x0b\n\x07TURN_ON\x10\x01\x12\x0c\n\x08TURN_OFF\x10\x02\x12\x10\n\x0c\x43HECK_BUTTON\x10\x03*f\n\nButtonType\x12\x17\n\x13\x42UTTON_DEFAULT_TYPE\x10\x00\x12\x0e\n\nCCD_SWITCH\x10\x01\x12\x0f\n\x0bTELE_SWITCH\x10\x02\x12\x0e\n\nFLAT_LIGHT\x10\x03\x12\x0e\n\nDOME_LIGHT\x10\x04*:\n\x0c\x42uttonStatus\x12\x19\n\x15\x42UTTON_DEFAULT_STATUS\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x07\n\x03OFF\x10\x02\x32\x66\n\x06\x42utton\x12,\n\tSetAction\x12\x0e.ButtonRequest\x1a\x0f.ButtonResponse\x12.\n\tGetStatus\x12\x0f.ButtonsRequest\x1a\x10.ButtonsResponseb\x06proto3')

_BUTTONACTION = DESCRIPTOR.enum_types_by_name['ButtonAction']
ButtonAction = enum_type_wrapper.EnumTypeWrapper(_BUTTONACTION)
_BUTTONTYPE = DESCRIPTOR.enum_types_by_name['ButtonType']
ButtonType = enum_type_wrapper.EnumTypeWrapper(_BUTTONTYPE)
_BUTTONSTATUS = DESCRIPTOR.enum_types_by_name['ButtonStatus']
ButtonStatus = enum_type_wrapper.EnumTypeWrapper(_BUTTONSTATUS)
BUTTON_DEFAULT_ACTION = 0
TURN_ON = 1
TURN_OFF = 2
CHECK_BUTTON = 3
BUTTON_DEFAULT_TYPE = 0
CCD_SWITCH = 1
TELE_SWITCH = 2
FLAT_LIGHT = 3
DOME_LIGHT = 4
BUTTON_DEFAULT_STATUS = 0
ON = 1
OFF = 2


_BUTTONSREQUEST = DESCRIPTOR.message_types_by_name['ButtonsRequest']
_BUTTONREQUEST = DESCRIPTOR.message_types_by_name['ButtonRequest']
_BUTTONSRESPONSE = DESCRIPTOR.message_types_by_name['ButtonsResponse']
_BUTTONRESPONSE = DESCRIPTOR.message_types_by_name['ButtonResponse']
_BUTTONGUI = DESCRIPTOR.message_types_by_name['ButtonGui']
_BUTTONCOLOR = DESCRIPTOR.message_types_by_name['ButtonColor']
_BUTTONIMAGE = DESCRIPTOR.message_types_by_name['ButtonImage']
_BUTTONIMAGESIZE = DESCRIPTOR.message_types_by_name['ButtonImageSize']
ButtonsRequest = _reflection.GeneratedProtocolMessageType('ButtonsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONSREQUEST,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonsRequest)
  })
_sym_db.RegisterMessage(ButtonsRequest)

ButtonRequest = _reflection.GeneratedProtocolMessageType('ButtonRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONREQUEST,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonRequest)
  })
_sym_db.RegisterMessage(ButtonRequest)

ButtonsResponse = _reflection.GeneratedProtocolMessageType('ButtonsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONSRESPONSE,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonsResponse)
  })
_sym_db.RegisterMessage(ButtonsResponse)

ButtonResponse = _reflection.GeneratedProtocolMessageType('ButtonResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONRESPONSE,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonResponse)
  })
_sym_db.RegisterMessage(ButtonResponse)

ButtonGui = _reflection.GeneratedProtocolMessageType('ButtonGui', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONGUI,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonGui)
  })
_sym_db.RegisterMessage(ButtonGui)

ButtonColor = _reflection.GeneratedProtocolMessageType('ButtonColor', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONCOLOR,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonColor)
  })
_sym_db.RegisterMessage(ButtonColor)

ButtonImage = _reflection.GeneratedProtocolMessageType('ButtonImage', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONIMAGE,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonImage)
  })
_sym_db.RegisterMessage(ButtonImage)

ButtonImageSize = _reflection.GeneratedProtocolMessageType('ButtonImageSize', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONIMAGESIZE,
  '__module__' : 'crac_protobuf.button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonImageSize)
  })
_sym_db.RegisterMessage(ButtonImageSize)

_BUTTON = DESCRIPTOR.services_by_name['Button']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUTTONACTION._serialized_start=719
  _BUTTONACTION._serialized_end=805
  _BUTTONTYPE._serialized_start=807
  _BUTTONTYPE._serialized_end=909
  _BUTTONSTATUS._serialized_start=911
  _BUTTONSTATUS._serialized_end=969
  _BUTTONSREQUEST._serialized_start=30
  _BUTTONSREQUEST._serialized_end=46
  _BUTTONREQUEST._serialized_start=48
  _BUTTONREQUEST._serialized_end=121
  _BUTTONSRESPONSE._serialized_start=123
  _BUTTONSRESPONSE._serialized_end=174
  _BUTTONRESPONSE._serialized_start=176
  _BUTTONRESPONSE._serialized_end=282
  _BUTTONGUI._serialized_start=285
  _BUTTONGUI._serialized_end=514
  _BUTTONCOLOR._serialized_start=516
  _BUTTONCOLOR._serialized_end=575
  _BUTTONIMAGE._serialized_start=577
  _BUTTONIMAGE._serialized_end=667
  _BUTTONIMAGESIZE._serialized_start=669
  _BUTTONIMAGESIZE._serialized_end=717
  _BUTTON._serialized_start=971
  _BUTTON._serialized_end=1073
# @@protoc_insertion_point(module_scope)
