# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crac_protobuf import camera_pb2 as crac__protobuf_dot_camera__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in crac_protobuf/camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CameraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAction = channel.unary_unary(
                '/Camera/SetAction',
                request_serializer=crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_camera__pb2.CameraResponse.FromString,
                _registered_method=True)
        self.Video = channel.unary_stream(
                '/Camera/Video',
                request_serializer=crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_camera__pb2.CameraResponse.FromString,
                _registered_method=True)
        self.ListCameras = channel.unary_unary(
                '/Camera/ListCameras',
                request_serializer=crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_camera__pb2.CamerasResponse.FromString,
                _registered_method=True)


class CameraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Video(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAction,
                    request_deserializer=crac__protobuf_dot_camera__pb2.CameraRequest.FromString,
                    response_serializer=crac__protobuf_dot_camera__pb2.CameraResponse.SerializeToString,
            ),
            'Video': grpc.unary_stream_rpc_method_handler(
                    servicer.Video,
                    request_deserializer=crac__protobuf_dot_camera__pb2.CameraRequest.FromString,
                    response_serializer=crac__protobuf_dot_camera__pb2.CameraResponse.SerializeToString,
            ),
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=crac__protobuf_dot_camera__pb2.CameraRequest.FromString,
                    response_serializer=crac__protobuf_dot_camera__pb2.CamerasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Camera', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Camera', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Camera(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Camera/SetAction',
            crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
            crac__protobuf_dot_camera__pb2.CameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Video(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Camera/Video',
            crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
            crac__protobuf_dot_camera__pb2.CameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Camera/ListCameras',
            crac__protobuf_dot_camera__pb2.CameraRequest.SerializeToString,
            crac__protobuf_dot_camera__pb2.CamerasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
