# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crac_protobuf/chart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63rac_protobuf/chart.proto\"b\n\x05\x43hart\x12\r\n\x05value\x18\x01 \x01(\x02\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1b\n\x13unit_of_measurement\x18\x07 \x01(\t\x12\x1e\n\nthresholds\x18\x06 \x03(\x0b\x32\n.Threshold\"U\n\tThreshold\x12\x0f\n\x07warning\x18\x01 \x01(\x02\x12\r\n\x05\x65rror\x18\x02 \x01(\x02\x12\x13\n\x0bupper_bound\x18\x03 \x01(\x02\x12\x13\n\x0blower_bound\x18\x04 \x01(\x02\"\x10\n\x0eWeatherRequest\"\xcf\x01\n\x0fWeatherResponse\x12\x1a\n\nwind_speed\x18\x01 \x01(\x0b\x32\x06.Chart\x12\x1f\n\x0fwind_gust_speed\x18\x02 \x01(\x0b\x32\x06.Chart\x12\x1b\n\x0btemperature\x18\x03 \x01(\x0b\x32\x06.Chart\x12\x18\n\x08humidity\x18\x04 \x01(\x0b\x32\x06.Chart\x12\x19\n\train_rate\x18\x05 \x01(\x0b\x32\x06.Chart\x12\x19\n\tbarometer\x18\x06 \x01(\x0b\x32\x06.Chart\x12\x12\n\nupdated_at\x18\x07 \x01(\x05\x32\x39\n\x07Weather\x12.\n\tGetStatus\x12\x0f.WeatherRequest\x1a\x10.WeatherResponseb\x06proto3')



_CHART = DESCRIPTOR.message_types_by_name['Chart']
_THRESHOLD = DESCRIPTOR.message_types_by_name['Threshold']
_WEATHERREQUEST = DESCRIPTOR.message_types_by_name['WeatherRequest']
_WEATHERRESPONSE = DESCRIPTOR.message_types_by_name['WeatherResponse']
Chart = _reflection.GeneratedProtocolMessageType('Chart', (_message.Message,), {
  'DESCRIPTOR' : _CHART,
  '__module__' : 'crac_protobuf.chart_pb2'
  # @@protoc_insertion_point(class_scope:Chart)
  })
_sym_db.RegisterMessage(Chart)

Threshold = _reflection.GeneratedProtocolMessageType('Threshold', (_message.Message,), {
  'DESCRIPTOR' : _THRESHOLD,
  '__module__' : 'crac_protobuf.chart_pb2'
  # @@protoc_insertion_point(class_scope:Threshold)
  })
_sym_db.RegisterMessage(Threshold)

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERREQUEST,
  '__module__' : 'crac_protobuf.chart_pb2'
  # @@protoc_insertion_point(class_scope:WeatherRequest)
  })
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERRESPONSE,
  '__module__' : 'crac_protobuf.chart_pb2'
  # @@protoc_insertion_point(class_scope:WeatherResponse)
  })
_sym_db.RegisterMessage(WeatherResponse)

_WEATHER = DESCRIPTOR.services_by_name['Weather']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHART._serialized_start=29
  _CHART._serialized_end=127
  _THRESHOLD._serialized_start=129
  _THRESHOLD._serialized_end=214
  _WEATHERREQUEST._serialized_start=216
  _WEATHERREQUEST._serialized_end=232
  _WEATHERRESPONSE._serialized_start=235
  _WEATHERRESPONSE._serialized_end=442
  _WEATHER._serialized_start=444
  _WEATHER._serialized_end=501
# @@protoc_insertion_point(module_scope)
