# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crac_protobuf/cover_mirror.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'crac_protobuf/cover_mirror.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crac_protobuf import button_pb2 as crac__protobuf_dot_button__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n crac_protobuf/cover_mirror.proto\x1a\x1a\x63rac_protobuf/button.proto\"8\n\x12\x43overMirrorRequest\x12\"\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x12.CoverMirrorAction\"Y\n\x13\x43overMirrorResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.CoverMirrorStatus\x12\x1e\n\nbutton_gui\x18\x02 \x01(\x0b\x32\n.ButtonGui*{\n\x11\x43overMirrorAction\x12\x1f\n\x1b\x43OVER_MIRROR_DEFAULT_ACTION\x10\x00\x12\x15\n\x11OPEN_COVER_MIRROR\x10\x01\x12\x16\n\x12\x43LOSE_COVER_MIRROR\x10\x02\x12\x16\n\x12\x43HECK_COVER_MIRROR\x10\x03*\xe5\x01\n\x11\x43overMirrorStatus\x12\x1f\n\x1b\x43OVER_MIRROR_DEFAULT_STATUS\x10\x00\x12\x17\n\x13\x43OVER_MIRROR_CLOSED\x10\x01\x12\x18\n\x14\x43OVER_MIRROR_STOPPED\x10\x02\x12\x17\n\x13\x43OVER_MIRROR_OPENED\x10\x03\x12\x18\n\x14\x43OVER_MIRROR_CLOSING\x10\x04\x12\x18\n\x14\x43OVER_MIRROR_OPENING\x10\x05\x12\x17\n\x13\x43OVER_MIRROR_DANGER\x10\x06\x12\x16\n\x12\x43OVER_MIRROR_ERROR\x10\x07\x32\x45\n\x0b\x43overMirror\x12\x36\n\tSetAction\x12\x13.CoverMirrorRequest\x1a\x14.CoverMirrorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crac_protobuf.cover_mirror_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COVERMIRRORACTION']._serialized_start=213
  _globals['_COVERMIRRORACTION']._serialized_end=336
  _globals['_COVERMIRRORSTATUS']._serialized_start=339
  _globals['_COVERMIRRORSTATUS']._serialized_end=568
  _globals['_COVERMIRRORREQUEST']._serialized_start=64
  _globals['_COVERMIRRORREQUEST']._serialized_end=120
  _globals['_COVERMIRRORRESPONSE']._serialized_start=122
  _globals['_COVERMIRRORRESPONSE']._serialized_end=211
  _globals['_COVERMIRROR']._serialized_start=570
  _globals['_COVERMIRROR']._serialized_end=639
# @@protoc_insertion_point(module_scope)
