# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'data_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_image.proto\"I\n\x0c\x43\x43\x44ImageData\x12\x1b\n\x13\x66ield_of_view_width\x18\x01 \x01(\x01\x12\x1c\n\x14\x66ield_of_view_height\x18\x02 \x01(\x01\"\x14\n\x12ImageConfigRequest2K\n\x12ImageConfigService\x12\x35\n\x0fGetCCDImageData\x12\x13.ImageConfigRequest\x1a\r.CCDImageDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CCDIMAGEDATA']._serialized_start=20
  _globals['_CCDIMAGEDATA']._serialized_end=93
  _globals['_IMAGECONFIGREQUEST']._serialized_start=95
  _globals['_IMAGECONFIGREQUEST']._serialized_end=115
  _globals['_IMAGECONFIGSERVICE']._serialized_start=117
  _globals['_IMAGECONFIGSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
