# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crac_protobuf import data_image_pb2 as crac__protobuf_dot_data__image__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crac_protobuf/data_image_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageConfigServiceStub(object):
    """Servizio per richiedere le configurazioni di generazione immagini
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCCDImageData = channel.unary_unary(
                '/ImageConfigService/GetCCDImageData',
                request_serializer=crac__protobuf_dot_data__image__pb2.ImageConfigRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_data__image__pb2.CCDImageData.FromString,
                _registered_method=True)


class ImageConfigServiceServicer(object):
    """Servizio per richiedere le configurazioni di generazione immagini
    """

    def GetCCDImageData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCCDImageData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCCDImageData,
                    request_deserializer=crac__protobuf_dot_data__image__pb2.ImageConfigRequest.FromString,
                    response_serializer=crac__protobuf_dot_data__image__pb2.CCDImageData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageConfigService(object):
    """Servizio per richiedere le configurazioni di generazione immagini
    """

    @staticmethod
    def GetCCDImageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageConfigService/GetCCDImageData',
            crac__protobuf_dot_data__image__pb2.ImageConfigRequest.SerializeToString,
            crac__protobuf_dot_data__image__pb2.CCDImageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
