# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crac_protobuf import geographic_pb2 as crac__protobuf_dot_geographic__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in crac_protobuf/geographic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeographicServiceStub(object):
    """Il servizio gRPC per richiedere le informazioni geografiche
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGeographicInfo = channel.unary_unary(
                '/GeographicService/GetGeographicInfo',
                request_serializer=crac__protobuf_dot_geographic__pb2.GeographicRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_geographic__pb2.GeographicData.FromString,
                _registered_method=True)


class GeographicServiceServicer(object):
    """Il servizio gRPC per richiedere le informazioni geografiche
    """

    def GetGeographicInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeographicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGeographicInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeographicInfo,
                    request_deserializer=crac__protobuf_dot_geographic__pb2.GeographicRequest.FromString,
                    response_serializer=crac__protobuf_dot_geographic__pb2.GeographicData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GeographicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GeographicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeographicService(object):
    """Il servizio gRPC per richiedere le informazioni geografiche
    """

    @staticmethod
    def GetGeographicInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeographicService/GetGeographicInfo',
            crac__protobuf_dot_geographic__pb2.GeographicRequest.SerializeToString,
            crac__protobuf_dot_geographic__pb2.GeographicData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
