# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geographic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'geographic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10geographic.proto\"O\n\x0eGeographicData\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x18\n\x10\x65levation_meters\x18\x03 \x01(\x01\"\x13\n\x11GeographicRequest2M\n\x11GeographicService\x12\x38\n\x11GetGeographicInfo\x12\x12.GeographicRequest\x1a\x0f.GeographicDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geographic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOGRAPHICDATA']._serialized_start=20
  _globals['_GEOGRAPHICDATA']._serialized_end=99
  _globals['_GEOGRAPHICREQUEST']._serialized_start=101
  _globals['_GEOGRAPHICREQUEST']._serialized_end=120
  _globals['_GEOGRAPHICSERVICE']._serialized_start=122
  _globals['_GEOGRAPHICSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
