# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crac_protobuf/roof.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crac_protobuf import button_pb2 as crac__protobuf_dot_button__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63rac_protobuf/roof.proto\x1a\x1a\x63rac_protobuf/button.proto\"?\n\x0bRoofRequest\x12\x1b\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0b.RoofAction\x12\x13\n\x0b\x61utodisplay\x18\x02 \x01(\x08\"K\n\x0cRoofResponse\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.RoofStatus\x12\x1e\n\nbutton_gui\x18\x02 \x01(\x0b\x32\n.ButtonGui*J\n\nRoofAction\x12\x17\n\x13ROOF_DEFAULT_ACTION\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x12\x0e\n\nCHECK_ROOF\x10\x03*\x9e\x01\n\nRoofStatus\x12\x17\n\x13ROOF_DEFAULT_STATUS\x10\x00\x12\x0f\n\x0bROOF_CLOSED\x10\x01\x12\x10\n\x0cROOF_STOPPED\x10\x02\x12\x0f\n\x0bROOF_OPENED\x10\x03\x12\x10\n\x0cROOF_CLOSING\x10\x04\x12\x10\n\x0cROOF_OPENING\x10\x05\x12\x0f\n\x0bROOF_DANGER\x10\x06\x12\x0e\n\nROOF_ERROR\x10\x07\x32\x30\n\x04Roof\x12(\n\tSetAction\x12\x0c.RoofRequest\x1a\r.RoofResponseb\x06proto3')

_ROOFACTION = DESCRIPTOR.enum_types_by_name['RoofAction']
RoofAction = enum_type_wrapper.EnumTypeWrapper(_ROOFACTION)
_ROOFSTATUS = DESCRIPTOR.enum_types_by_name['RoofStatus']
RoofStatus = enum_type_wrapper.EnumTypeWrapper(_ROOFSTATUS)
ROOF_DEFAULT_ACTION = 0
OPEN = 1
CLOSE = 2
CHECK_ROOF = 3
ROOF_DEFAULT_STATUS = 0
ROOF_CLOSED = 1
ROOF_STOPPED = 2
ROOF_OPENED = 3
ROOF_CLOSING = 4
ROOF_OPENING = 5
ROOF_DANGER = 6
ROOF_ERROR = 7


_ROOFREQUEST = DESCRIPTOR.message_types_by_name['RoofRequest']
_ROOFRESPONSE = DESCRIPTOR.message_types_by_name['RoofResponse']
RoofRequest = _reflection.GeneratedProtocolMessageType('RoofRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOFREQUEST,
  '__module__' : 'crac_protobuf.roof_pb2'
  # @@protoc_insertion_point(class_scope:RoofRequest)
  })
_sym_db.RegisterMessage(RoofRequest)

RoofResponse = _reflection.GeneratedProtocolMessageType('RoofResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROOFRESPONSE,
  '__module__' : 'crac_protobuf.roof_pb2'
  # @@protoc_insertion_point(class_scope:RoofResponse)
  })
_sym_db.RegisterMessage(RoofResponse)

_ROOF = DESCRIPTOR.services_by_name['Roof']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOFACTION._serialized_start=198
  _ROOFACTION._serialized_end=272
  _ROOFSTATUS._serialized_start=275
  _ROOFSTATUS._serialized_end=433
  _ROOFREQUEST._serialized_start=56
  _ROOFREQUEST._serialized_end=119
  _ROOFRESPONSE._serialized_start=121
  _ROOFRESPONSE._serialized_end=196
  _ROOF._serialized_start=435
  _ROOF._serialized_end=483
# @@protoc_insertion_point(module_scope)
