# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from crac_protobuf import telescope_pb2 as crac__protobuf_dot_telescope__pb2


class TelescopeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAction = channel.unary_unary(
                '/Telescope/SetAction',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                )
        self.EqMove = channel.unary_unary(
                '/Telescope/EqMove',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                )
        self.AAMove = channel.unary_unary(
                '/Telescope/AAMove',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                )


class TelescopeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EqMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AAMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelescopeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAction,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
            'EqMove': grpc.unary_unary_rpc_method_handler(
                    servicer.EqMove,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
            'AAMove': grpc.unary_unary_rpc_method_handler(
                    servicer.AAMove,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Telescope', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Telescope(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telescope/SetAction',
            crac__protobuf_dot_telescope__pb2.TelescopeRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EqMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telescope/EqMove',
            crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AAMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telescope/AAMove',
            crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
