# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crac_protobuf import telescope_pb2 as crac__protobuf_dot_telescope__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in crac_protobuf/telescope_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TelescopeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAction = channel.unary_unary(
                '/Telescope/SetAction',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                _registered_method=True)
        self.EqMove = channel.unary_unary(
                '/Telescope/EqMove',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                _registered_method=True)
        self.AAMove = channel.unary_unary(
                '/Telescope/AAMove',
                request_serializer=crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.SerializeToString,
                response_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
                _registered_method=True)


class TelescopeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EqMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AAMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelescopeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAction,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
            'EqMove': grpc.unary_unary_rpc_method_handler(
                    servicer.EqMove,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
            'AAMove': grpc.unary_unary_rpc_method_handler(
                    servicer.AAMove,
                    request_deserializer=crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.FromString,
                    response_serializer=crac__protobuf_dot_telescope__pb2.TelescopeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Telescope', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Telescope', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Telescope(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Telescope/SetAction',
            crac__protobuf_dot_telescope__pb2.TelescopeRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EqMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Telescope/EqMove',
            crac__protobuf_dot_telescope__pb2.TelescopeEquatorialMovementRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AAMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Telescope/AAMove',
            crac__protobuf_dot_telescope__pb2.TelescopeAltazimutalMovementRequest.SerializeToString,
            crac__protobuf_dot_telescope__pb2.TelescopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
