# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crac_protobuf/ups.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'crac_protobuf/ups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crac_protobuf import chart_pb2 as crac__protobuf_dot_chart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63rac_protobuf/ups.proto\x1a\x19\x63rac_protobuf/chart.proto\"{\n\x0bUpsResponse\x12\x12\n\nupdated_at\x18\x07 \x01(\x05\x12\x19\n\x06\x63harts\x18\x08 \x03(\x0b\x32\t.UpsChart\x12\x1a\n\x06status\x18\t \x01(\x0e\x32\n.UpsStatus\x12\x10\n\x08interval\x18\n \x01(\x05\x12\x0f\n\x07\x64\x65vices\x18\x0b \x03(\t\"\x0c\n\nUpsRequest\"K\n\x08UpsChart\x12\x15\n\x05\x63hart\x18\x01 \x01(\x0b\x32\x06.Chart\x12(\n\x10\x62\x61ttery_statuses\x18\x02 \x03(\x0e\x32\x0e.BatteryStatus*m\n\tUpsStatus\x12\x1a\n\x16UPS_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11UPS_STATUS_NORMAL\x10\x01\x12\x16\n\x12UPS_STATUS_WARNING\x10\x02\x12\x15\n\x11UPS_STATUS_DANGER\x10\x03*\xa5\x01\n\rBatteryStatus\x12\x1e\n\x1a\x42\x41TTERY_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x42\x41TTERY_STATUS_DISCHARGE\x10\x01\x12\x19\n\x15\x42\x41TTERY_STATUS_ONLINE\x10\x02\x12\x1c\n\x18\x42\x41TTERY_STATUS_ONBATTERY\x10\x03\x12\x1d\n\x19\x42\x41TTERY_STATUS_LOWBATTERY\x10\x04\x32-\n\x03Ups\x12&\n\tGetStatus\x12\x0b.UpsRequest\x1a\x0c.UpsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crac_protobuf.ups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPSSTATUS']._serialized_start=270
  _globals['_UPSSTATUS']._serialized_end=379
  _globals['_BATTERYSTATUS']._serialized_start=382
  _globals['_BATTERYSTATUS']._serialized_end=547
  _globals['_UPSRESPONSE']._serialized_start=54
  _globals['_UPSRESPONSE']._serialized_end=177
  _globals['_UPSREQUEST']._serialized_start=179
  _globals['_UPSREQUEST']._serialized_end=191
  _globals['_UPSCHART']._serialized_start=193
  _globals['_UPSCHART']._serialized_end=268
  _globals['_UPS']._serialized_start=549
  _globals['_UPS']._serialized_end=594
# @@protoc_insertion_point(module_scope)
