# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crac_protobuf/ups.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crac_protobuf import chart_pb2 as crac__protobuf_dot_chart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63rac_protobuf/ups.proto\x1a\x19\x63rac_protobuf/chart.proto\"x\n\x0bUpsResponse\x12\x12\n\nupdated_at\x18\x07 \x01(\x05\x12\x16\n\x06\x63harts\x18\x08 \x03(\x0b\x32\x06.Chart\x12\x1a\n\x06status\x18\t \x01(\x0e\x32\n.UpsStatus\x12\x10\n\x08interval\x18\n \x01(\x05\x12\x0f\n\x07\x64\x65vices\x18\x0b \x03(\t\"\x0c\n\nUpsRequest*m\n\tUpsStatus\x12\x1a\n\x16UPS_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11UPS_STATUS_NORMAL\x10\x01\x12\x16\n\x12UPS_STATUS_WARNING\x10\x02\x12\x15\n\x11UPS_STATUS_DANGER\x10\x03\x32-\n\x03Ups\x12&\n\tGetStatus\x12\x0b.UpsRequest\x1a\x0c.UpsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crac_protobuf.ups_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPSSTATUS._serialized_start=190
  _UPSSTATUS._serialized_end=299
  _UPSRESPONSE._serialized_start=54
  _UPSRESPONSE._serialized_end=174
  _UPSREQUEST._serialized_start=176
  _UPSREQUEST._serialized_end=188
  _UPS._serialized_start=301
  _UPS._serialized_end=346
# @@protoc_insertion_point(module_scope)
