# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roof.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roof.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nroof.proto\"/\n\x0bRoofRequest\x12 \n\x0broof_action\x18\x01 \x01(\x0e\x32\x0b.RoofAction\"0\n\x0cRoofResponse\x12 \n\x0broof_status\x18\x01 \x01(\x0e\x32\x0b.RoofStatus*,\n\nRoofAction\x12\x08\n\x04OPEN\x10\x00\x12\t\n\x05\x43LOSE\x10\x01\x12\t\n\x05\x43HECK\x10\x02*b\n\nRoofStatus\x12\n\n\x06\x43LOSED\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\n\n\x06OPENED\x10\x02\x12\x0b\n\x07\x43LOSING\x10\x03\x12\x0b\n\x07OPENING\x10\x04\x12\n\n\x06\x44\x41NGER\x10\x05\x12\t\n\x05\x45RROR\x10\x06\x32\x30\n\x04Roof\x12(\n\tSetAction\x12\x0c.RoofRequest\x1a\r.RoofResponseb\x06proto3'
)

_ROOFACTION = _descriptor.EnumDescriptor(
  name='RoofAction',
  full_name='RoofAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=113,
  serialized_end=157,
)
_sym_db.RegisterEnumDescriptor(_ROOFACTION)

RoofAction = enum_type_wrapper.EnumTypeWrapper(_ROOFACTION)
_ROOFSTATUS = _descriptor.EnumDescriptor(
  name='RoofStatus',
  full_name='RoofStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DANGER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=159,
  serialized_end=257,
)
_sym_db.RegisterEnumDescriptor(_ROOFSTATUS)

RoofStatus = enum_type_wrapper.EnumTypeWrapper(_ROOFSTATUS)
OPEN = 0
CLOSE = 1
CHECK = 2
CLOSED = 0
STOPPED = 1
OPENED = 2
CLOSING = 3
OPENING = 4
DANGER = 5
ERROR = 6



_ROOFREQUEST = _descriptor.Descriptor(
  name='RoofRequest',
  full_name='RoofRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='roof_action', full_name='RoofRequest.roof_action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=61,
)


_ROOFRESPONSE = _descriptor.Descriptor(
  name='RoofResponse',
  full_name='RoofResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='roof_status', full_name='RoofResponse.roof_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=111,
)

_ROOFREQUEST.fields_by_name['roof_action'].enum_type = _ROOFACTION
_ROOFRESPONSE.fields_by_name['roof_status'].enum_type = _ROOFSTATUS
DESCRIPTOR.message_types_by_name['RoofRequest'] = _ROOFREQUEST
DESCRIPTOR.message_types_by_name['RoofResponse'] = _ROOFRESPONSE
DESCRIPTOR.enum_types_by_name['RoofAction'] = _ROOFACTION
DESCRIPTOR.enum_types_by_name['RoofStatus'] = _ROOFSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoofRequest = _reflection.GeneratedProtocolMessageType('RoofRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOFREQUEST,
  '__module__' : 'roof_pb2'
  # @@protoc_insertion_point(class_scope:RoofRequest)
  })
_sym_db.RegisterMessage(RoofRequest)

RoofResponse = _reflection.GeneratedProtocolMessageType('RoofResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROOFRESPONSE,
  '__module__' : 'roof_pb2'
  # @@protoc_insertion_point(class_scope:RoofResponse)
  })
_sym_db.RegisterMessage(RoofResponse)



_ROOF = _descriptor.ServiceDescriptor(
  name='Roof',
  full_name='Roof',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=259,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetAction',
    full_name='Roof.SetAction',
    index=0,
    containing_service=None,
    input_type=_ROOFREQUEST,
    output_type=_ROOFRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROOF)

DESCRIPTOR.services_by_name['Roof'] = _ROOF

# @@protoc_insertion_point(module_scope)
