# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.3
    - name: Install package
      run: poetry install --no-dev
    - name: Build package
      run: poetry build
    - name: Upload Asset
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
      uses: PeerXu/upload-asset@v1
      with:
        # which file to upload
        file: dist/crac-protobuf-0.1.10.tar.gz
